// Publisher ActionType

export const PUBLISHER_LOGIN_REQUEST = "PUBLISHER_LOGIN_REQUEST";
export const PUBLISHER_LOGIN_SUCCESS = "PUBLISHER_LOGIN_SUCCESS";
export const PUBLISHER_LOGIN_FAILURE = "PUBLISHER_LOGIN_FAILURE";

export const PUBLISHER_LOGOUT = "PUBLISHER_LOGOUT";

export const PUBLISHER_REGISTER_REQUEST = "PUBLISHER_REGISTER_REQUEST";
export const PUBLISHER_REGISTER_SUCCESS = "PUBLISHER_REGISTER_SUCCESS";
export const PUBLISHER_REGISTER_FAILURE = "PUBLISHER_REGISTER_FAILURE";

export const UPLOAD_FILE_REQUEST = "UPLOAD_FILE_REQUEST";
export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS";
export const UPLOAD_FILE_FAILURE = "UPLOAD_FILE_FAILURE";

// export const GET_BOOK_REQUEST = "GET_BOOK_REQUEST"
// export const GET_BOOK_SUCCESS = "GET_BOOK_SUCCESS"
// export const GET_BOOK_FAILURE = "UPLOAD_FILE_FAILURE"

export const GET_BOOK_ID_REQUEST = "GET_BOOK_ID_REQUEST";
export const GET_BOOK_ID_SUCCESS = "GET_BOOK_ID_SUCCESS";
export const GET_BOOK_ID_FAILURE = "GET_BOOK_ID_FAILURE";

export const GET_BOOK_CAT_REQUEST = "GET_BOOK_CAT_REQUEST";
export const GET_BOOK_CAT_SUCCESS = "GET_BOOK_CAT_SUCCESS";
export const GET_BOOK_CAT_FAILURE = "GET_BOOK_CAT_FAILURE";

export const DEL_BOOK_REQUEST = "DEL_BOOK_REQUEST";
export const DEL_BOOK_SUCCESS = "DEL_BOOK_SUCCESS";
export const DEL_BOOK_FAILURE = "DEL_BOOK_FAILURE";

export const ADD_CATEGORY_REQUEST = "ADD_CATEGORY_REQUEST";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAILURE = "ADD_CATEGORY_FAILURE";

export const GET_CATEGORY_REQUEST = "GET_CATEGORY_REQUEST";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAILURE = "GET_CATEGORY_FAILURE";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE";
