// Publisher ActionType

export const PUBLISHER_LOGIN_REQUEST = "PUBLISHER_LOGIN_REQUEST";
export const PUBLISHER_LOGIN_SUCCESS = "PUBLISHER_LOGIN_SUCCESS";
export const PUBLISHER_LOGIN_FAILURE = "PUBLISHER_LOGIN_FAILURE";

export const PUBLISHER_LOGOUT = "PUBLISHER_LOGOUT";

export const PUBLISHER_REGISTER_REQUEST = "PUBLISHER_REGISTER_REQUEST";
export const PUBLISHER_REGISTER_SUCCESS = "PUBLISHER_REGISTER_SUCCESS";
export const PUBLISHER_REGISTER_FAILURE = "PUBLISHER_REGISTER_FAILURE";

export const UPLOAD_FILE_REQUEST = "UPLOAD_FILE_REQUEST";
export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS";
export const UPLOAD_FILE_FAILURE = "UPLOAD_FILE_FAILURE";

export const GET_BOOK_REQUEST = "GET_BOOK_REQUEST";
export const GET_BOOK_SUCCESS = "GET_BOOK_SUCCESS";
export const GET_BOOK_FAILURE = "UPLOAD_FILE_FAILURE";

export const GET_BOOK_ID_REQUEST = "GET_BOOK_ID_REQUEST";
export const GET_BOOK_ID_SUCCESS = "GET_BOOK_ID_SUCCESS";
export const GET_BOOK_ID_FAILURE = "GET_BOOK_ID_FAILURE";

export const GET_BOOK_CAT_REQUEST = "GET_BOOK_CAT_REQUEST";
export const GET_BOOK_CAT_SUCCESS = "GET_BOOK_CAT_SUCCESS";
export const GET_BOOK_CAT_FAILURE = "GET_BOOK_CAT_FAILURE";

export const DEL_BOOK_REQUEST = "DEL_BOOK_REQUEST";
export const DEL_BOOK_SUCCESS = "DEL_BOOK_SUCCESS";
export const DEL_BOOK_FAILURE = "DEL_BOOK_FAILURE";

export const ADD_CATEGORY_REQUEST = "ADD_CATEGORY_REQUEST";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAILURE = "ADD_CATEGORY_FAILURE";

export const GET_CATEGORY_REQUEST = "GET_CATEGORY_REQUEST";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAILURE = "GET_CATEGORY_FAILURE";

export const ADD_SUBSCRIBER_REQUEST = "ADD_SUBSCRIBER_REQUEST";
export const ADD_SUBSCRIBER_SUCCESS = "ADD_SUBSCRIBER_SUCCESS";
export const ADD_SUBSCRIBER_FAILURE = "ADD_SUBSCRIBER_FAILURE";

//User ActionType

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE";

export const PURCHASEBOOK_REQUEST = "PURCHASEBOOK_REQUEST";
export const PURCHASEBOOK_SUCCESS = "PURCHASEBOOK_SUCCESS";
export const PURCHASEBOOK_FAILURE = "PURCHASEBOOK_FAILURE";

export const GET_PURCHASEBOOK_REQUEST = "GET_PURCHASEBOOK_REQUEST";
export const GET_PURCHASEBOOK_SUCCESS = "GET_PURCHASEBOOK_SUCCESS";
export const GET_PURCHASEBOOK_FAILURE = "GET_PURCHASEBOOK_FAILURE";

export const ADD_CARTBOOK_REQUEST = "ADD_CARTBOOK_REQUEST";
export const ADD_CARTBOOK_SUCCESS = "ADD_CARTBOOK_SUCCESS";
export const ADD_CARTBOOK_FAILURE = "ADD_CARTBOOK_FAILURE";

export const GET_CARTBOOK_REQUEST = "GET_CARTBOOK_REQUEST";
export const GET_CARTBOOK_SUCCESS = "GET_CARTBOOK_SUCCESS";
export const GET_CARTBOOK_FAILURE = "GET_CARTBOOK_FAILURE";

export const DEL_CARTBOOK_REQUEST = "DEL_CARTBOOK_REQUEST";
export const DEL_CARTBOOK_SUCCESS = "DEL_CARTBOOK_SUCCESS";
export const DEL_CARTBOOK_FAILURE = "DEL_CARTBOOK_FAILURE";

export const ADD_WISHLISTBOOK_REQUEST = "ADD_WISHLISTBOOK_REQUEST";
export const ADD_WISHLISTBOOK_SUCCESS = "ADD_WISHLISTBOOK_SUCCESS";
export const ADD_WISHLISTBOOK_FAILURE = "ADD_WISHLISTBOOK_FAILURE";

export const GET_WISHLISTBOOK_REQUEST = "GET_WISHLISTBOOK_REQUEST";
export const GET_WISHLISTBOOK_SUCCESS = "GET_WISHLISTBOOK_SUCCESS";
export const GET_WISHLISTBOOK_FAILURE = "GET_WISHLISTBOOK_FAILURE";

export const DEL_WISHLISTBOOK_REQUEST = "DEL_WISHLISTBOOK_REQUEST";
export const DEL_WISHLISTBOOK_SUCCESS = "DEL_WISHLISTBOOK_SUCCESS";
export const DEL_WISHLISTBOOK_FAILURE = "DEL_WISHLISTBOOK_FAILURE";

export const GET_USERBOOKSUG_REQUEST = "GET_USERBOOKSUG_REQUEST";
export const GET_USERBOOKSUG_SUCCESS = "GET_USERBOOKSUG_SUCCESS";
export const GET_USERBOOKSUG_FAILURE = "GET_USERBOOKSUG_FAILURE";

export const GET_USERBOOKBYID_REQUEST = "GET_USERBOOKBYID_REQUEST";
export const GET_USERBOOKBYID_SUCCESS = "GET_USERBOOKBYID_SUCCESS";
export const GET_USERBOOKBYID_FAILURE = "GET_USERBOOKBYID_FAILURE";

export const GET_USERBOOKBYCAT_REQUEST = "GET_USERBOOKBYCAT_REQUEST";
export const GET_USERBOOKBYCAT_SUCCESS = "GET_USERBOOKBYCAT_SUCCESS";
export const GET_USERBOOKBYCAT_FAILURE = "GET_USERBOOKBYCAT_FAILURE";

export const GET_READERSUB_REQUEST = "GET_READERSUB_REQUEST";
export const GET_READERSUB_SUCCESS = "GET_READERSUB_SUCCESS";
export const GET_READERSUB_FAILURE = "GET_READERSUB_FAILURE";

export const ADD_READERSUB_REQUEST = "ADD_READERSUB_REQUEST";
export const ADD_READERSUB_SUCCESS = "ADD_READERSUB_SUCCESS";
export const ADD_READERSUB_FAILURE = "ADD_READERSUB_FAILURE";

//REACT-READER

export const ADD_BOOKHIGHLIGHT_REQUEST = "ADD_BOOKHIGHLIGHT_REQUEST";
export const ADD_BOOKHIGHLIGHT_SUCCESS = "ADD_BOOKHIGHLIGHT_SUCCESS";
export const ADD_BOOKHIGHLIGHT_FAILURE = "ADD_BOOKHIGHLIGHT_FAILURE";

export const GET_BOOKHIGHLIGHT_REQUEST = "GET_BOOKHIGHLIGHT_REQUEST";
export const GET_BOOKHIGHLIGHT_SUCCESS = "GET_BOOKHIGHLIGHT_SUCCESS";
export const GET_BOOKHIGHLIGHT_FAILURE = "GET_BOOKHIGHLIGHT_FAILURE";

export const ADD_BOOKNOTES_REQUEST = "ADD_BOOKNOTES_REQUEST";
export const ADD_BOOKNOTES_SUCCESS = "ADD_BOOKNOTES_SUCCESS";
export const ADD_BOOKNOTES_FAILURE = "ADD_BOOKNOTES_FAILURE";

export const GET_BOOKNOTES_REQUEST = "GET_BOOKNOTES_REQUEST";
export const GET_BOOKNOTES_SUCCESS = "GET_BOOKNOTES_SUCCESS";
export const GET_BOOKNOTES_FAILURE = "GET_BOOKNOTES_FAILURE";

export const UPDATE_PROGRESS_REQUEST = "UPDATE_PROGRESS_REQUEST";
export const UPDATE_PROGRESS_SUCCESS = "UPDATE_PROGRESS_SUCCESS";
export const UPDATE_PROGRESS_FAILURE = "UPDATE_PROGRESS_FAILURE";

export const GET_PROGRESS_REQUEST = "GET_PROGRESS_REQUEST";
export const GET_PROGRESS_SUCCESS = "GET_PROGRESS_SUCCESS";
export const GET_PROGRESS_FAILURE = "GET_PROGRESS_FAILURE";

//Chatbot

export const POST_USERQUES_REQUEST = "POST_USERQUES_REQUEST";
export const POST_USERQUES_SUCCESS = "POST_USERQUES_SUCCESS";
export const POST_USERQUES_FAILURE = "POST_USERQUES_FAILURE";
