import Cover1 from "../Components/Assets/cover1.avif";
import Cover2 from "../Components/Assets/cover2.avif";
import Cover3 from "../Components/Assets/cover3.avif";
import cover from "../Components/Assets/book_cover1.jpg";
import cover4 from "../Components/Assets/book_cover2.jpg";
import cover5 from "../Components/Assets/book_cover3.jpg";
import cover6 from "../Components/Assets/book_cover4.jpg";
import cover7 from "../Components/Assets/book_cover5.jpg";

export const RegisteredData = [
  {
    userName: "Publisher",
    Email: "publisher@gmail.com",
    Password: "PUblish",
    Role: "Publisher",
  },
  {
    userName: "User",
    Email: "User@gmail.com",
    Password: "User",
    Role: "User",
  },
];

export const Book_list = [
  {
    book_id: 1,
    Book_cover: cover,
    title: "The Art Of Lover",
    author: "Author",
    language: "English",
    genre: "Romance",
    price: 200,
    rental_price: 100,
    Rental_duration: 1,
    preview: "",
    discription:
      "'Soul' by Olivia Wilson is a touching romance about love and memory, where one partner must fight to rekindle a lost relationship after an accident. It’s a story of resilience, proving that true love can overcome even the deepest forgetfulness.",
  },
  {
    book_id: 2,
    Book_cover: Cover1,
    title: "Our Last Summer",
    author: "Claudia Wilson",
    language: "English",
    genre: "Romance",
    price: 200,
    rental_price: 100,
    Rental_duration: 1,
    preview: "",
    discription:
      "'Soul' by Olivia Wilson is a touching romance about love and memory, where one partner must fight to rekindle a lost relationship after an accident. It’s a story of resilience, proving that true love can overcome even the deepest forgetfulness.",
  },
  {
    book_id: 3,
    Book_cover: Cover2,
    title: "Tales Under a Purple Sky",
    author: "Samira Hadid",
    language: "English",
    genre: "Romance",
    price: 200,
    rental_price: 100,
    Rental_duration: 1,
    preview: "",
    discription:
      "'Soul' by Olivia Wilson is a touching romance about love and memory, where one partner must fight to rekindle a lost relationship after an accident. It’s a story of resilience, proving that true love can overcome even the deepest forgetfulness.",
  },
  {
    book_id: 4,
    Book_cover: Cover3,
    title: "My Story",
    author: "Hannh Morales",
    language: "English",
    genre: "Romance",
    price: 200,
    rental_price: 100,
    Rental_duration: 1,
    preview: "",
    discription:
      "'Soul' by Olivia Wilson is a touching romance about love and memory, where one partner must fight to rekindle a lost relationship after an accident. It’s a story of resilience, proving that true love can overcome even the deepest forgetfulness.",
  },
  {
    book_id: 5,
    Book_cover: cover4,
    title: "The Art Of Lover",
    author: "Author",
    language: "English",
    genre: "Romance",
    price: 200,
    rental_price: 100,
    Rental_duration: 1,
    preview: "",
    discription:
      "'Soul' by Olivia Wilson is a touching romance about love and memory, where one partner must fight to rekindle a lost relationship after an accident. It’s a story of resilience, proving that true love can overcome even the deepest forgetfulness.",
  },
  {
    book_id: 6,
    Book_cover: cover5,
    title: "Our Last Summer",
    author: "Claudia Wilson",
    language: "English",
    genre: "Romance",
    price: 200,
    rental_price: 100,
    Rental_duration: 1,
    preview: "",
    discription:
      "'Soul' by Olivia Wilson is a touching romance about love and memory, where one partner must fight to rekindle a lost relationship after an accident. It’s a story of resilience, proving that true love can overcome even the deepest forgetfulness.",
  },
  {
    book_id: 7,
    Book_cover: cover6,
    title: "Tales Under a Purple Sky",
    author: "Samira Hadid",
    language: "English",
    genre: "Romance",
    price: 200,
    rental_price: 100,
    Rental_duration: 1,
    preview: "",
    discription:
      "'Soul' by Olivia Wilson is a touching romance about love and memory, where one partner must fight to rekindle a lost relationship after an accident. It’s a story of resilience, proving that true love can overcome even the deepest forgetfulness.",
  },
  {
    book_id: 8,
    Book_cover: cover7,
    title: "My Story",
    author: "Hannh Morales",
    language: "English",
    genre: "Romance",
    price: 200,
    rental_price: 100,
    Rental_duration: 1,
    preview: "",
    discription:
      "'Soul' by Olivia Wilson is a touching romance about love and memory, where one partner must fight to rekindle a lost relationship after an accident. It’s a story of resilience, proving that true love can overcome even the deepest forgetfulness.",
  },
];

export const books = [
  {
    author: "Sriram",
    book_id: 17,
    category_id: 5,
    created_at: "2025-03-19 05:06:05",
    description: null,
    e_book_type: "epub",
    epub_file: "17.epub.enc",
    genre: "Tech",
    isbn: "1234567890123",
    language: "English",
    offer_price: "None",
    price: "100",
    rental_price: "10",
    status: "pending",
    title: "JavaScript Tutorial",
    updated_at: "2025-03-19 05:06:05",
  },
  {
    author: "Sriram",
    book_id: 20,
    category_id: 6,
    created_at: "2025-03-19 05:54:28",
    description: null,
    e_book_type: "epub",
    epub_file: "20.epub.enc",
    genre: "Tech",
    isbn: "1234567890123",
    language: "English",
    offer_price: "None",
    price: "100",
    rental_price: "10",
    status: "live",
    title: "test14",
    updated_at: "2025-03-19 05:54:28",
  },
  {
    author: "Sriram",
    book_id: 26,
    category_id: 7,
    created_at: "2025-03-19 08:53:09",
    description: null,
    e_book_type: "epub",
    epub_file: "21.epub",
    genre: "Tech",
    isbn: "1234567890123",
    language: "English",
    offer_price: "None",
    price: "100",
    rental_price: "10",
    status: "live",
    title: "test16",
    updated_at: "2025-03-19 08:53:09",
  },
  {
    author: "Sriram",
    book_id: 27,
    category_id: 7,
    created_at: "2025-03-19 08:53:13",
    description: null,
    e_book_type: "epub",
    epub_file: "27.epub",
    genre: "Tech",
    isbn: "1234567890123",
    language: "English",
    offer_price: "None",
    price: "100",
    rental_price: "10",
    status: "pending",
    title: "test16",
    updated_at: "2025-03-19 08:53:13",
  },
  {
    author: "Sriram",
    book_id: 28,
    category_id: 7,
    created_at: "2025-03-20 08:40:53",
    description: null,
    e_book_type: "epub",
    epub_file: "28.epub",
    genre: "Tech",
    isbn: "1234567890123",
    language: "English",
    offer_price: "None",
    price: "100",
    rental_price: "10",
    status: "live",
    title: "test17",
    updated_at: "2025-03-20 08:40:53",
  },
  {
    author: "Sriram",
    book_id: 29,
    category_id: 7,
    created_at: "2025-03-20 09:48:51",
    description: null,
    e_book_type: "epub",
    epub_file: "29.epub",
    genre: "Tech",
    isbn: "1234567890123",
    language: "English",
    offer_price: "None",
    price: "100",
    rental_price: "10",
    status: "pending",
    title: "test17",
    updated_at: "2025-03-20 09:48:51",
  },
  {
    author: "Sriram",
    book_id: 30,
    category_id: 7,
    created_at: "2025-03-21 06:43:21",
    description: null,
    e_book_type: "epub",
    epub_file: "30.epub",
    genre: "Tech",
    isbn: "1234567890123",
    language: "English",
    offer_price: "None",
    price: "100",
    rental_price: "10",
    status: "pending",
    title: "test17",
    updated_at: "2025-03-21 06:43:21",
  },
  {
    author: "Sriram",
    book_id: 31,
    category_id: 7,
    created_at: "2025-03-21 06:46:02",
    description: null,
    e_book_type: "epub",
    epub_file: "31.epub",
    genre: "Tech",
    isbn: "1234567890123",
    language: "English",
    offer_price: "None",
    price: "100",
    rental_price: "10",
    status: "pending",
    title: "test17",
    updated_at: "2025-03-21 06:46:02",
  },
  {
    author: "Sriram",
    book_id: 32,
    category_id: 7,
    created_at: "2025-03-21 06:50:48",
    description: null,
    e_book_type: "epub",
    epub_file: "32.epub",
    genre: "Tech",
    isbn: "1234567890123",
    language: "English",
    offer_price: "None",
    price: "100",
    rental_price: "10",
    status: "pending",
    title: "test17",
    updated_at: "2025-03-21 06:50:48",
  },
  {
    author: "Sriram",
    book_id: 33,
    category_id: 7,
    created_at: "2025-03-21 07:25:10",
    description: null,
    e_book_type: "epub",
    epub_file: "33.epub",
    genre: "Romance",
    isbn: "1234567890123",
    language: "English",
    offer_price: "None",
    price: "100",
    rental_price: "10",
    status: "pending",
    title: "test17",
    updated_at: "2025-03-21 07:25:10",
  },
  {
    author: "Sriram",
    book_id: 34,
    category_id: 7,
    created_at: "2025-03-21 09:25:14",
    description: null,
    e_book_type: "epub",
    epub_file: "34.epub",
    genre: "Tech",
    isbn: "1234567890123",
    language: "English",
    offer_price: "None",
    price: "100",
    rental_price: "10",
    status: "live",
    title: "test19",
    updated_at: "2025-03-21 09:25:14",
  },
  {
    author: "Sriram",
    book_id: 35,
    category_id: 7,
    created_at: "2025-03-21 09:27:14",
    description: null,
    e_book_type: "epub",
    epub_file: "35.epub",
    genre: "Tech",
    isbn: "1234567890123",
    language: "English",
    offer_price: "200",
    price: "100",
    rental_price: "10",
    status: "live",
    title: "test20",
    updated_at: "2025-03-21 09:27:14",
  },
  {
    author: "Sriram",
    book_id: 36,
    category_id: 7,
    created_at: "2025-03-21 09:39:29",
    description: null,
    e_book_type: "epub",
    epub_file: "36.epub",
    genre: "Romance",
    isbn: "1234567890123",
    language: "English",
    offer_price: "200",
    price: "100",
    rental_price: "10",
    status: "pending",
    title: "test20",
    updated_at: "2025-03-21 09:39:29",
  },
];
